# -*- coding: utf-8 -*-
"""imgscrapBing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GoOe3nYvEpuGEdY_TBj1KgKZ7Z3IBBDb
"""

!pip install bing-image-downloader

!mkdir dataset_latolato

from bing_image_downloader import downloader
downloader.download("mainan lato lato", limit=15, output_dir='dataset_latolato')

