# -*- coding: utf-8 -*-
"""imgscrap_google.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oaNb-Q_VMr6AuBs93nH4qbt05iGn2m8g
"""

!pip install google_images_search requests

import os
import requests
from google_images_search import GoogleImagesSearch

# Ganti dengan API key dan Search Engine ID Anda
gis = GoogleImagesSearch('AIzaSyCSqAh-j-VTAkFtf5a0l3mUdW_tRwnSxLk', '4541603497d5f44fa')

# Parameter pencarian
search_params = {
    'q': 'lato lato',  # Query pencarian
    'num': 1,          # Jumlah gambar yang diambil
    'safe': 'off',   # Tingkat keamanan pencarian (low, medium, high)
}

# Lakukan pencarian
gis.search(search_params)

# Buat direktori untuk menyimpan gambar
save_directory = '/content/downloaded_images'
os.makedirs(save_directory, exist_ok=True)

# Unduh dan simpan gambar
for i, image in enumerate(gis.results()):
    image_url = image.url
    response = requests.get(image_url)

    # Tentukan path untuk menyimpan gambar
    image_path = os.path.join(save_directory, f'image_{i+1}.jpg')

    # Simpan gambar ke file
    with open(image_path, 'wb') as file:
        file.write(response.content)

    print(f'Image {i+1} saved at: {image_path}')

!rm -r downloaded_images

